using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Wprawka1.Data;
using Wprawka1.Helpers;
using Wprawka1.Models;

namespace Wprawka1.Controllers
{
    public class AccountController : Controller
    {
        private readonly BookstoreContext _context;

        public AccountController(BookstoreContext context)
        {
            _context = context;
        }
        // <auto-generated />
        // --- REJESTRACJA ---
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(User user, string plainPassword)
        {
            if (_context.Users.Any(u => u.Login == user.Login))
            {
                ModelState.AddModelError("Login", "Ten login jest już zajęty.");
            }

            if (ModelState.IsValid && !string.IsNullOrEmpty(plainPassword))
            {
                user.PasswordHash = PasswordHelper.HashPassword(plainPassword);

                _context.Users.Add(user);
                await _context.SaveChangesAsync();

                return RedirectToAction("Login");
            }

            return View(user);
        }
        // <auto-generated />
        // --- LOGOWANIE ---
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(string login, string password)
        {
            if (string.IsNullOrEmpty(login) || string.IsNullOrEmpty(password))
            {
                ModelState.AddModelError("", "Podaj login i hasło.");
                return View();
            }

            string hashedInput = PasswordHelper.HashPassword(password);
            var user = _context.Users.FirstOrDefault(u => u.Login == login && u.PasswordHash == hashedInput);

            if (user != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.Login!),
                    new Claim("FullName", $"{user.FirstName} {user.LastName}")
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                return RedirectToAction("Index", "Books");
            }

            ModelState.AddModelError("", "Nieprawidłowy login lub hasło.");
            return View();
        }
        // <auto-generated />
        // --- WYLOGOWANIE ---
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}